### ISSUE TITLE
remove `napari.run()` from ipynb files

### ISSUE THREAD

**Issue by tlambert03** [BiAPoL/on_the_fly_image_processing_napari#1]
quick note: `napari.run()` [doesn't do anything in ipython notebook files](https://napari.org/guides/stable/event_loop.html#in-ipython-or-jupyter-notebook) (unless the user has specifically gone into the settings and disabled the ipython features)

**Comment by haesleinhuepf** [comment]
Cool! Thanks for the hint! I will also let the students know :-)
